# Generated by Django 3.2.5 on 2021-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
