# Generated by Django 3.2.5 on 2021-11-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosite', '0002_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contents',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
