# Generated by Django 3.2.5 on 2021-12-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosite', '0003_alter_task_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
