# Generated by Django 3.2.5 on 2021-12-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosite', '0004_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
