# Generated by Django 3.2.5 on 2022-01-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosite', '0007_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_id',
            field=models.IntegerField(default=0),
        ),
    ]
