# Generated by Django 3.2.5 on 2022-01-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todosite', '0008_task_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='custom_id',
        ),
    ]
